# -*- coding: utf-8 -*-
"""Zomato_Bangalore_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IhMNb-Uv5SMwAdbOTsNxZb2DxnniEJ2b
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline

df = pd.read_csv("zomato.csv")

df.head()

df.shape

df.columns

df.info()

df.isnull().sum()

df.drop(['url','phone'],axis=1,inplace=True)

df.head()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

df['rate'].unique()

df['rate'] = df['rate'].replace(
    ['NEW','-'],
    np.nan
)

df['rate'] = df['rate'].str.split('/').str[0]

df['rate'].head()

df['rate'] = df['rate'].astype(float)

df['rate'].dtype

df['approx_cost(for two people)'].head()

df['approx_cost(for two people)'] = \
df['approx_cost(for two people)'].astype(str)

df['approx_cost(for two people)'] = \
df['approx_cost(for two people)'].str.replace(',','')

df['approx_cost(for two people)'] = \
df['approx_cost(for two people)'].astype(float)

plt.figure(figsize=(10,5))

sns.histplot(
    df['rate'],
    bins=20,
    kde=True
)

plt.title("Restaurant Ratings Distribution")

plt.show()

sns.countplot(
    x='online_order',
    data=df
)

plt.title("Online Ordering Availability")

plt.show()

sns.countplot(
    x='book_table',
    data=df
)

plt.title("Table Booking Availability")

plt.show()

top_locations = df['location'].value_counts().head(10)

top_locations

plt.figure(figsize=(12,6))

top_locations.plot(kind='bar')

plt.title("Top 10 Restaurant Locations")

plt.show()

cuisine = (
    df['cuisines']
    .dropna()
    .str.split(',')
    .explode()
)

cuisine.value_counts().head(10)

cuisine.value_counts().head(10).plot(
    kind='bar'
)

plt.title("Top Cuisines")

plt.show()

plt.figure(figsize=(10,5))

sns.histplot(
    df['approx_cost(for two people)'],
    bins=40
)

plt.title("Cost Distribution")

plt.show()

plt.figure(figsize=(10,6))

sns.scatterplot(
    x='approx_cost(for two people)',
    y='rate',
    data=df
)

plt.show()